services:
  postgres:
    image: postgres:16
    container_name: ${APP_NAME}-postgres
    hostname: ${APP_NAME}-db
    working_dir: /application
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/postgres:/application
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5432:5432'

  webserver:
    image: nginx:alpine
    container_name: ${APP_NAME}-webserver
    hostname: ${APP_NAME}-nginx
    working_dir: /application
    volumes:
      - ./:/application
      - ./docker/nginx/ssl:/etc/ssl
      - ./docker/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/templates/ssl-proxy.conf.template:/etc/nginx/conf.d/ssl-proxy.conf
    depends_on:
      - php-fpm
    ports:
      - '80:80'
      - '443:443'

  php-fpm:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${APP_NAME}-php-fpm
    hostname: ${APP_NAME}
    working_dir: /application
    restart: unless-stopped
    volumes:
      - ./:/application
      - ./docker/php-fpm/20-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php-fpm/99-overrides.ini:/usr/local/etc/php/conf.d/zzz-overrides.ini
    depends_on:
      - postgres
    ports:
      - '9000:9000'
